# Form implementation generated from reading ui file 'CornholeScorekeeperRawGuiV0.1.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 845)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CornholeBoardFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.CornholeBoardFrame.setGeometry(QtCore.QRect(290, 80, 211, 341))
        self.CornholeBoardFrame.setStyleSheet("QFrame#CornholeBoardFrame {\n"
"    background-color: #c89b63;\n"
"    border: 3px solid #5c3b1e;\n"
"    border-radius: 12px;\n"
"}")
        self.CornholeBoardFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CornholeBoardFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CornholeBoardFrame.setObjectName("CornholeBoardFrame")
        self.CornholeBoardHole = QtWidgets.QFrame(parent=self.CornholeBoardFrame)
        self.CornholeBoardHole.setGeometry(QtCore.QRect(40, 20, 120, 120))
        self.CornholeBoardHole.setMaximumSize(QtCore.QSize(120, 120))
        self.CornholeBoardHole.setStyleSheet("QFrame#CornholeBoardHole {\n"
"    background-color: #2b2b2b;\n"
"    border-radius: 50px;\n"
"}")
        self.CornholeBoardHole.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CornholeBoardHole.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CornholeBoardHole.setObjectName("CornholeBoardHole")
        self.RedBag4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag4.setGeometry(QtCore.QRect(360, 170, 31, 31))
        self.RedBag4.setStyleSheet("QFrame#RedBag1, QFrame#RedBag2, QFrame#RedBag3, QFrame#RedBag4 {\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag4.setObjectName("RedBag4")
        self.RedBag3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag3.setGeometry(QtCore.QRect(340, 150, 31, 31))
        self.RedBag3.setStyleSheet("QFrame#RedBag1, QFrame#RedBag2, QFrame#RedBag3, QFrame#RedBag4 {\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag3.setObjectName("RedBag3")
        self.RedBag2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag2.setGeometry(QtCore.QRect(360, 130, 31, 31))
        self.RedBag2.setStyleSheet("QFrame#RedBag1, QFrame#RedBag2, QFrame#RedBag3, QFrame#RedBag4 {\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag2.setObjectName("RedBag2")
        self.RedBag1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag1.setGeometry(QtCore.QRect(350, 120, 31, 31))
        self.RedBag1.setStyleSheet("QFrame#RedBag1, QFrame#RedBag2, QFrame#RedBag3, QFrame#RedBag4 {\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag1.setObjectName("RedBag1")
        self.BlueBag1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag1.setGeometry(QtCore.QRect(390, 110, 31, 31))
        self.BlueBag1.setStyleSheet("QFrame#BlueBag1, QFrame#BlueBag2, QFrame#BlueBag3, QFrame#BlueBag4 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag1.setObjectName("BlueBag1")
        self.BlueBag2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag2.setGeometry(QtCore.QRect(410, 130, 31, 31))
        self.BlueBag2.setStyleSheet("QFrame#BlueBag1, QFrame#BlueBag2, QFrame#BlueBag3, QFrame#BlueBag4 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag2.setObjectName("BlueBag2")
        self.BlueBag4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag4.setGeometry(QtCore.QRect(390, 170, 31, 31))
        self.BlueBag4.setStyleSheet("QFrame#BlueBag1, QFrame#BlueBag2, QFrame#BlueBag3, QFrame#BlueBag4 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag4.setObjectName("BlueBag4")
        self.BlueBag3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag3.setGeometry(QtCore.QRect(400, 150, 31, 31))
        self.BlueBag3.setStyleSheet("QFrame#BlueBag1, QFrame#BlueBag2, QFrame#BlueBag3, QFrame#BlueBag4 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag3.setObjectName("BlueBag3")
        self.RedBag1_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag1_2.setGeometry(QtCore.QRect(320, 240, 31, 31))
        self.RedBag1_2.setStyleSheet("QFrame#RedBag1_2, QFrame#RedBag2_2, QFrame#RedBag3_2, QFrame#RedBag4 _2{\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag1_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag1_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag1_2.setObjectName("RedBag1_2")
        self.RedBag2_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag2_2.setGeometry(QtCore.QRect(340, 280, 31, 31))
        self.RedBag2_2.setStyleSheet("QFrame#RedBag1_2, QFrame#RedBag2_2, QFrame#RedBag3_2, QFrame#RedBag4 _2{\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag2_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag2_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag2_2.setObjectName("RedBag2_2")
        self.RedBag3_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag3_2.setGeometry(QtCore.QRect(320, 320, 31, 31))
        self.RedBag3_2.setStyleSheet("QFrame#RedBag1_2, QFrame#RedBag2_2, QFrame#RedBag3_2, QFrame#RedBag4 _2{\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag3_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag3_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag3_2.setObjectName("RedBag3_2")
        self.RedBag4_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.RedBag4_2.setGeometry(QtCore.QRect(340, 350, 31, 31))
        self.RedBag4_2.setStyleSheet("QFrame#RedBag1_2, QFrame#RedBag2_2, QFrame#RedBag3_2, QFrame#RedBag4_2{\n"
"    background-color: #c0392b;\n"
"    border: 2px solid #7b241c;\n"
"    border-radius: 6px;\n"
"}")
        self.RedBag4_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RedBag4_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RedBag4_2.setObjectName("RedBag4_2")
        self.BlueBag1_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag1_2.setGeometry(QtCore.QRect(420, 240, 31, 31))
        self.BlueBag1_2.setStyleSheet("QFrame#BlueBag1_2, QFrame#BlueBag2_2, QFrame#BlueBag3_2, QFrame#BlueBag4_2 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag1_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag1_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag1_2.setObjectName("BlueBag1_2")
        self.BlueBag2_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag2_2.setGeometry(QtCore.QRect(410, 280, 31, 31))
        self.BlueBag2_2.setStyleSheet("QFrame#BlueBag1_2, QFrame#BlueBag2_2, QFrame#BlueBag3_2, QFrame#BlueBag4_2 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag2_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag2_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag2_2.setObjectName("BlueBag2_2")
        self.BlueBag3_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag3_2.setGeometry(QtCore.QRect(420, 310, 31, 31))
        self.BlueBag3_2.setStyleSheet("QFrame#BlueBag1_2, QFrame#BlueBag2_2, QFrame#BlueBag3_2, QFrame#BlueBag4_2 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag3_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag3_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag3_2.setObjectName("BlueBag3_2")
        self.BlueBag4_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.BlueBag4_2.setGeometry(QtCore.QRect(400, 350, 31, 31))
        self.BlueBag4_2.setStyleSheet("QFrame#BlueBag1_2, QFrame#BlueBag2_2, QFrame#BlueBag3_2, QFrame#BlueBag4_2 {\n"
"    background-color: #2980b9;\n"
"    border: 2px solid #1f618d;\n"
"    border-radius: 6px;\n"
"}")
        self.BlueBag4_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlueBag4_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlueBag4_2.setObjectName("BlueBag4_2")
        self.CornholeTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.CornholeTitle.setGeometry(QtCore.QRect(200, 0, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.CornholeTitle.setFont(font)
        self.CornholeTitle.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.CornholeTitle.setObjectName("CornholeTitle")
        self.PlusHoleRedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PlusHoleRedButton.setGeometry(QtCore.QRect(80, 140, 75, 23))
        self.PlusHoleRedButton.setStyleSheet("QPushButton {color: red}")
        self.PlusHoleRedButton.setObjectName("PlusHoleRedButton")
        self.MinusHoleRedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MinusHoleRedButton.setGeometry(QtCore.QRect(80, 180, 75, 23))
        self.MinusHoleRedButton.setStyleSheet("QPushButton {color: red}")
        self.MinusHoleRedButton.setObjectName("MinusHoleRedButton")
        self.PlusBoardRedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PlusBoardRedButton.setGeometry(QtCore.QRect(80, 260, 75, 23))
        self.PlusBoardRedButton.setStyleSheet("QPushButton {color: red}")
        self.PlusBoardRedButton.setObjectName("PlusBoardRedButton")
        self.MinusBoardRedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MinusBoardRedButton.setGeometry(QtCore.QRect(80, 310, 75, 23))
        self.MinusBoardRedButton.setStyleSheet("QPushButton {color: red}")
        self.MinusBoardRedButton.setObjectName("MinusBoardRedButton")
        self.PlusHoleBlueButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PlusHoleBlueButton.setGeometry(QtCore.QRect(620, 140, 75, 23))
        self.PlusHoleBlueButton.setStyleSheet("QPushButton {color: #2980b9}")
        self.PlusHoleBlueButton.setObjectName("PlusHoleBlueButton")
        self.MinusHoleBlueButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MinusHoleBlueButton.setGeometry(QtCore.QRect(620, 180, 75, 23))
        self.MinusHoleBlueButton.setStyleSheet("QPushButton {color: #2980b9}")
        self.MinusHoleBlueButton.setObjectName("MinusHoleBlueButton")
        self.PlusBoardBlueButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PlusBoardBlueButton.setGeometry(QtCore.QRect(620, 270, 75, 23))
        self.PlusBoardBlueButton.setStyleSheet("QPushButton {color: #2980b9}")
        self.PlusBoardBlueButton.setObjectName("PlusBoardBlueButton")
        self.MinusBoardBlueButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MinusBoardBlueButton.setGeometry(QtCore.QRect(620, 320, 75, 23))
        self.MinusBoardBlueButton.setStyleSheet("QPushButton {color: #2980b9}")
        self.MinusBoardBlueButton.setObjectName("MinusBoardBlueButton")
        self.ConfirmRoundButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ConfirmRoundButton.setGeometry(QtCore.QRect(360, 510, 81, 31))
        self.ConfirmRoundButton.setObjectName("ConfirmRoundButton")
        self.RedScoreTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.RedScoreTitle.setGeometry(QtCore.QRect(60, 550, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.RedScoreTitle.setFont(font)
        self.RedScoreTitle.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: 800;\n"
"    color: red;\n"
"}")
        self.RedScoreTitle.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.RedScoreTitle.setObjectName("RedScoreTitle")
        self.BlueScoreTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.BlueScoreTitle.setGeometry(QtCore.QRect(580, 540, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.BlueScoreTitle.setFont(font)
        self.BlueScoreTitle.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: 800;\n"
"    color: #2980b9;\n"
"}")
        self.BlueScoreTitle.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.BlueScoreTitle.setObjectName("BlueScoreTitle")
        self.ScoreLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoreLabel.setGeometry(QtCore.QRect(240, 460, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ScoreLabel.setFont(font)
        self.ScoreLabel.setObjectName("ScoreLabel")
        self.RedScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.RedScore.setGeometry(QtCore.QRect(80, 590, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.RedScore.setFont(font)
        self.RedScore.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: 800;\n"
"    color: red;\n"
"}")
        self.RedScore.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.RedScore.setObjectName("RedScore")
        self.BlueScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.BlueScore.setGeometry(QtCore.QRect(600, 590, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.BlueScore.setFont(font)
        self.BlueScore.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: 800;\n"
"    color: #2980b9;\n"
"}")
        self.BlueScore.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.BlueScore.setObjectName("BlueScore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CornholeTitle.setText(_translate("MainWindow", "Cornhole Scorekeeper"))
        self.PlusHoleRedButton.setText(_translate("MainWindow", "+"))
        self.MinusHoleRedButton.setText(_translate("MainWindow", "-"))
        self.PlusBoardRedButton.setText(_translate("MainWindow", "+"))
        self.MinusBoardRedButton.setText(_translate("MainWindow", "-"))
        self.PlusHoleBlueButton.setText(_translate("MainWindow", "+"))
        self.MinusHoleBlueButton.setText(_translate("MainWindow", "-"))
        self.PlusBoardBlueButton.setText(_translate("MainWindow", "+"))
        self.MinusBoardBlueButton.setText(_translate("MainWindow", "-"))
        self.ConfirmRoundButton.setText(_translate("MainWindow", "Confirm Round"))
        self.RedScoreTitle.setText(_translate("MainWindow", "Red Score"))
        self.BlueScoreTitle.setText(_translate("MainWindow", "Blue Score"))
        self.ScoreLabel.setText(_translate("MainWindow", "Round Score: [score] for [Red or Blue]"))
        self.RedScore.setText(_translate("MainWindow", "[score]"))
        self.BlueScore.setText(_translate("MainWindow", "[score]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
