# Form implementation generated from reading ui file 'VotingMachineRawGuiV0.1.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 90, 221, 191))
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.VoteButton = QtWidgets.QPushButton(parent=self.MainPage)
        self.VoteButton.setGeometry(QtCore.QRect(70, 50, 75, 23))
        self.VoteButton.setObjectName("VoteButton")
        self.ViewButton = QtWidgets.QPushButton(parent=self.MainPage)
        self.ViewButton.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.ViewButton.setObjectName("ViewButton")
        self.stackedWidget.addWidget(self.MainPage)
        self.VotePage = QtWidgets.QWidget()
        self.VotePage.setObjectName("VotePage")
        self.JohnButton = QtWidgets.QRadioButton(parent=self.VotePage)
        self.JohnButton.setGeometry(QtCore.QRect(70, 40, 82, 17))
        self.JohnButton.setObjectName("JohnButton")
        self.JaneButton = QtWidgets.QRadioButton(parent=self.VotePage)
        self.JaneButton.setGeometry(QtCore.QRect(70, 70, 82, 17))
        self.JaneButton.setObjectName("JaneButton")
        self.ConfirmVoteButton = QtWidgets.QPushButton(parent=self.VotePage)
        self.ConfirmVoteButton.setGeometry(QtCore.QRect(70, 110, 75, 23))
        self.ConfirmVoteButton.setObjectName("ConfirmVoteButton")
        self.BackFromVotingButton = QtWidgets.QPushButton(parent=self.VotePage)
        self.BackFromVotingButton.setGeometry(QtCore.QRect(80, 140, 51, 20))
        self.BackFromVotingButton.setObjectName("BackFromVotingButton")
        self.IDLabel = QtWidgets.QLabel(parent=self.VotePage)
        self.IDLabel.setGeometry(QtCore.QRect(36, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.ErrorLabel = QtWidgets.QLabel(parent=self.VotePage)
        self.ErrorLabel.setGeometry(QtCore.QRect(60, 159, 121, 31))
        self.ErrorLabel.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    font-weight: 800;\n"
"    color: red;\n"
"}")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.IDTextBox = QtWidgets.QLineEdit(parent=self.VotePage)
        self.IDTextBox.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.IDTextBox.setObjectName("IDTextBox")
        self.stackedWidget.addWidget(self.VotePage)
        self.ViewPage = QtWidgets.QWidget()
        self.ViewPage.setObjectName("ViewPage")
        self.JohnVotesLabel = QtWidgets.QLabel(parent=self.ViewPage)
        self.JohnVotesLabel.setGeometry(QtCore.QRect(60, 20, 101, 16))
        self.JohnVotesLabel.setObjectName("JohnVotesLabel")
        self.JaneVotesLabel = QtWidgets.QLabel(parent=self.ViewPage)
        self.JaneVotesLabel.setGeometry(QtCore.QRect(60, 50, 101, 16))
        self.JaneVotesLabel.setObjectName("JaneVotesLabel")
        self.BackFromViewerButton = QtWidgets.QPushButton(parent=self.ViewPage)
        self.BackFromViewerButton.setGeometry(QtCore.QRect(80, 100, 51, 20))
        self.BackFromViewerButton.setObjectName("BackFromViewerButton")
        self.stackedWidget.addWidget(self.ViewPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Machine"))
        self.VoteButton.setText(_translate("MainWindow", "Vote"))
        self.ViewButton.setText(_translate("MainWindow", "Viewer"))
        self.JohnButton.setText(_translate("MainWindow", "John"))
        self.JaneButton.setText(_translate("MainWindow", "Jane"))
        self.ConfirmVoteButton.setText(_translate("MainWindow", "Vote"))
        self.BackFromVotingButton.setText(_translate("MainWindow", "Menu"))
        self.IDLabel.setText(_translate("MainWindow", "ID"))
        self.ErrorLabel.setText(_translate("MainWindow", "Enter valid ID"))
        self.JohnVotesLabel.setText(_translate("MainWindow", "Votes for John:"))
        self.JaneVotesLabel.setText(_translate("MainWindow", "Votes for Jane:"))
        self.BackFromViewerButton.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
